iplay/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.http import HttpResponseRedirect

from todo import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('todo.urls')),
]

todo/urls.py
from django.conf.urls import url

from . import views

app_name = 'todo'

urlpatterns = [
  url(r'^$', views.index, name='index'),
  url(r'^tasklist_update$', views.tasklist_update, name='tasklist_update'),
]

todo/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.
@python_2_unicode_compatible
class Task(models.Model):
  description = models.CharField(max_length=256)
  due_by = models.DateField(default=None, blank=True, null=True)

  def __str__(self):
    return self.description

todo/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.utils import timezone
from .models import Task

import datetime

# Create your views here.
def index(request):
  all_tasks = Task.objects.all()
  template = loader.get_template('todo/index.html')
  context = {
    'all_tasks' : all_tasks
  }
  return HttpResponse(template.render(context, request))

def tasklist_update(request):
  aDescription = request.POST['description']
  if(aDescription):
    aDueBy = request.POST['due_by']

    if(aDueBy):
      aDueBy = datetime.datetime.strptime(aDueBy, "%m/%d/%Y")
      t = Task(description=aDescription, due_by=aDueBy)
    else:
      t = Task(description=aDescription)

    t.save()

  else:
    try:
      aRemoval = [key for key, value in request.POST.items() if key.startswith('remove')][0].split('_')[1]
      if(aRemoval):
        Task.objects.filter(id=aRemoval).delete()
    except:
      pass

  return HttpResponseRedirect(reverse('todo:index'))

todo/templates/todo/index.html
{%load static %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="{% static 'todo/style.css' %}">
<link href="https://fonts.googleapis.com/css?family=Karla" rel="stylesheet">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>
  $(function () {
    $("#datepicker").datepicker();
  })
</script>

<form action="{% url 'todo:tasklist_update' %}" method="post">

<div id='iPlay'>

  <h1>i play Extra Credit</h1>

  {% csrf_token %}

  {% if all_tasks %}
    <div class='task-header'>
      <div id='task-description-hdr'>Task</div><div id='task-due-hdr'>Due</div><div id='task-complete-hdr'>Done?</div>
    </div>
    {% for t in all_tasks %}
      <div class='task-row'>
        <div class='task-item' id='task-description'>{{t.description}}</div><div class='task-item' id='task-due'>{{t.due_by}}</div><div class='task-item' id='task-complete'><input type="submit" name="remove_{{t.id}}" value="Done!"></div>
      </div>  
    {% endfor %}
  {% else %}
    <p>No Tasks Found!</p>
  {% endif %}
</div>

<div id='add-task-box'>
  <h3>Add Task</h3>
  <div id="left-column">
    <div>
      <div class="form-title">Description:</div> 
      <input type="text" name="description"/>
    </div>
    <div>
      <div class="form-title">Due:</div>
      <input type="text" id="datepicker" name="due_by">
    </div>
  </div>
  <div class="form-submit">
    <input type="submit" name="Add Task!" value="Add Task!" />
  </div>
</div>

</form>